In [1]:
# import external dependencies
# ----------------------------

# set the backend
import matplotlib
matplotlib.use('nbagg') # set plotting backend
import matplotlib.pyplot as plt
plt.ion()

# standard packages
import numpy as np
import pandas as pd

# propagator models
import propagator as prop

import scorr

In [282]:
from scorr._cov_matrices_nofft import xmat3pt_nofft

In [2]:
prop.tim1([1,0,0,0], [1,.5,0,0])

array([  1.00000000e+00,   5.00000000e-01,   0.00000000e+00,
         2.77555756e-17])

In [3]:
scorr.acorr([1,0,0,0], subtract_mean=False, norm='cov')

array([ 0.25,  0.  ,  0.  ,  0.  ])

In [4]:
prop.response([1,.5,0,0], [1,0,0,0])

(array([-2, -1,  0,  1,  2]),
 array([ 0.   ,  0.   ,  0.25 ,  0.125,  0.   ]),
 array([-0.   , -0.   ,  0.   ,  0.25 ,  0.375]))

In [678]:
s = np.array([1,-1,-1,1,-1])
c = np.array([1,1,0,1,1],dtype=bool)
#kc = np.array([1,.9,.8,.7,.6])
#kn = np.array([0,.1,.1,.1,.1])
#r  = np.array([ 1. ,  0. , -0.1, -0. ])
maxlag = len(s) -1

In [688]:
#steps  = 32
#maxlag = steps
#s = 2 * (np.random.rand(steps) > 0.5) - 1
#c = np.random.rand(steps) > 0.5
kc = np.ones(maxlag)
kn = 0.1 * np.ones(maxlag)
#kn[0] = 0

In [689]:
r = prop.hdim2(s, c, kn, kc)

In [690]:
r

array([  1.00000000e+00,   1.11022302e-16,  -0.00000000e+00,
         9.00000000e-01,  -1.10000000e+00])

In [691]:
x3kw = {'nfft':2*maxlag, 'pad':maxlag, 'subtract_mean':False, 'norm':'cov'}
Cccc = scorr.x3corr(c, s*c, s*c, **x3kw)[:maxlag,:maxlag]
Cnnc = scorr.x3corr(c, s*(~c), s*(~c), **x3kw)[:maxlag,:maxlag]
Ccnc = scorr.x3corr(c, s*(~c), s*(~c), **x3kw)[:maxlag,:maxlag]
Sn   = prop.response(r, s*(~c), maxlag=maxlag, ret='s')
Sc   = prop.response(r, s*c, maxlag=maxlag, ret='s')

In [692]:
Sn.shape, Sc.shape, maxlag

((7,), (7,), 4)

In [693]:
Cccc.shape, Cnnc.shape, Ccnc.shape

((4, 4), (4, 4), (4, 4))

In [694]:
Ccnc.round(2)

array([[ 0.  ,  0.  , -0.  ,  0.  ],
       [ 0.  ,  0.33,  0.  ,  0.  ],
       [-0.  ,  0.  ,  0.25,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ]])

In [695]:
knest, kcest = prop.estimate_hdim2(
    Cnnc, Cccc, Ccnc, Sn, Sc,
    maxlag=maxlag
)

In [696]:
knest.round(2), kcest.round(2)

(array([ -0.00000000e+00,   2.00000000e-02,   6.90000000e-01,
         -5.32358713e+15]), array([-0.27, -0.4 ,  0.19,  0.76]))

In [698]:
kc

array([ 1.,  1.,  1.,  1.])